kind: Service 
apiVersion: v1 
metadata: 
  labels:
    app: productui 
  name: productui-service 
spec: 
  selector: 
    app: productui 
  ports: 
  - protocol: TCP 
    port: 8081
    name: productuiport 
  type: ClusterIP 