apiVersion: apps/v1
kind: Deployment
metadata:
  name: productui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productui
    spec:
      containers:
      - name: productui
        image: shibus/product-ui-angular:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: productui
spec:
  selector:
    name: productui
  ports:
  - name: default
    protocol: TCP
    port: 4200
    targetPort: 4200